FUCarRentingSystemFE/FUCarRentingSystemFE/Controllers/CarInformationController.cs
using System.Threading.Tasks;
using BusinessObjects;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using BusinessObjects.Models;
using System.Text;

namespace FUCarRentingSystemFE.Controllers
{
    public class CarInformationController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public CarInformationController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", loginModel);
            }

            try
            {
                var client = _httpClientFactory.CreateClient();
                client.BaseAddress = new Uri("http://localhost:5173/api/"); // Adjust the base URL as needed.

                var loginJson = JsonConvert.SerializeObject(loginModel);
                var content = new StringContent(loginJson, Encoding.UTF8, "application/json");

                var response = await client.PostAsync("Customer/login", content);

                if (response.IsSuccessStatusCode)
                {
                    // Login was successful. You can perform further actions here.
                    return RedirectToAction("Success"); // Redirect to a success action or view.
                }
                else
                {
                    // Login failed. Handle the error accordingly.
                    ModelState.AddModelError(string.Empty, "Invalid username or password.");
                    return View("Index", loginModel);
                }
            }
            catch (Exception ex)
            {
                // Handle any exceptions that may occur during the API call.
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                return View("Index", loginModel);
            }
        }

    }
}

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/CustomerPages/CarInformation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Models;
using Newtonsoft.Json;
using System.Net.Http;
using Microsoft.IdentityModel.Tokens;
using static FUCarRentingSystemFE.Pages.CustomerPages.CarInformationModel;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Net.Http.Headers;

namespace FUCarRentingSystemFE.Pages.CustomerPages
{
    public class CarInformationModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string Keyword { get; set; }
        public String CustomerMessage { get; set; }
        public List<CarInformation> CarInformation { get; set; } = new List<CarInformation>();
        private readonly IHttpClientFactory _httpClientFactory;

        public CarInformationModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> OnGet()
        {
            int? customerId = HttpContext.Session.GetInt32("CustomerId") ??0;
            if (customerId == 0)
                return RedirectToPage("/NotAuthorized");
            string token = HttpContext.Session.GetString("token") ?? null;
            CustomerMessage = HttpContext.Session.GetString("CustomerMessage");
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var response = await client.GetAsync("CarInformation");

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    CarInformation = JsonConvert.DeserializeObject<List<CarInformation>>(responseContent);
                    foreach (CarInformation carInformation in CarInformation)
                        if (carInformation.CarStatus == 0)
                            CarInformation.Remove(carInformation);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            string token = HttpContext.Session.GetString("token") ?? null;
            if (Keyword == null)
                return RedirectToPage("./Index");
            else
                try
                {
                    var client = _httpClientFactory.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    client.BaseAddress = new Uri("http://localhost:5071/api/");
                    var response = await client.GetAsync("CarInformation/search?keyword=" + Keyword);

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();
                        CarInformation = JsonConvert.DeserializeObject<List<CarInformation>>(responseContent);
                        foreach (CarInformation carInformation in CarInformation)
                            if (carInformation.CarStatus == 0)
                                CarInformation.Remove(carInformation);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                }
            return Page();
        }
    } 
}

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/CustomerPages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using SimpleShoppingCartSession.Models;
using System.Linq;
using System.Data;
using BusinessObjects.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using DocumentFormat.OpenXml.Office2010.Excel;
using System.Net.Http.Headers;

namespace FUCarRentingSystemFE.Pages.CustomerPages
{

    public class CartModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public CartModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public List<Item> cart { get; set; }
        public decimal Total { get; set; }
        public async Task<IActionResult> OnGet()
        {
            int? customerId = HttpContext.Session.GetInt32("CustomerId") ?? 0;
            if (customerId == 0)
                return RedirectToPage("/NotAuthorized");
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            Total = cart.Sum(i => i.CarInformation.CarRentingPricePerDay * i.TotalDays);
            return Page();

        }

            public async Task<IActionResult> OnGetBuyNow(int id)
            {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                Item item = new Item();
                item.CarInformation = await GetCarInformationAsync(id);
                item.StartDate = DateTime.Now;
                item.EndDate = DateTime.Now;
                item.TotalDays = 1;
                item.Total = item.CarInformation.CarRentingPricePerDay * item.TotalDays;
                cart.Add(item);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new Item
                    {
                        CarInformation = await GetCarInformationAsync(id),
                        StartDate = DateTime.Now,
                        TotalDays =1,
                        EndDate = DateTime.Now,
                    });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }
        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        public void CalculateTotal()
        {
            Total = 0; // Initialize total

            foreach (var item in cart)
            {
                // Calculate the number of days between StartDate and EndDat

                // Add the subtotal to the total
                Total += item.Total;
            }
        }

        // ... other methods ...
        public IActionResult OnPostUpdate(DateTime[] startDate, DateTime[] endDate, decimal[] total)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].StartDate = startDate[i];
                cart[i].EndDate = endDate[i];
                if (cart[i].StartDate > cart[i].EndDate)
                    cart[i].TotalDays = 0;
                else
                    cart[i].TotalDays = (int)(cart[i].EndDate - cart[i].StartDate).TotalDays + 1;
                cart[i].Total = total[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            CalculateTotal();
            return RedirectToPage("Cart");
        }

        public async Task<IActionResult> OnPostBuynow()
        {
            int? customerId = HttpContext.Session.GetInt32("CustomerId") ?? 0;
            if (customerId == 0)
                return RedirectToPage("/NotAuthorized");
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            Total = cart.Sum(i => i.CarInformation.CarRentingPricePerDay * i.TotalDays);
            if (Total <= 0)
            {
                HttpContext.Session.SetString("CustomerMessage", "Can not rent. Nothing for rent!");
                return RedirectToPage("/CustomerPages/CarInformation");
            }
            List<RentingDetail> rentingDetails = new List<RentingDetail>();
            foreach(Item item in cart)
            {
                rentingDetails.Add(new RentingDetail
                {
                    CarId = item.CarInformation.CarId,
                    StartDate = item.StartDate,
                    EndDate = item.EndDate,
                    RentingTransactionId =1
                });
            }
            List<bool> checkList = await CheckCarExist(rentingDetails);
            if (checkList.Contains(false))
            {
                string context= "Can not rent, car ";
                for (int i = 0; i < checkList.Count; i++)
                {
                    if (checkList[i] == false)
                    {
                        context += "("+cart[i].CarInformation.CarName + ") ";
                    }
                }
                context += "had been rented for that days.";
                HttpContext.Session.SetString("CustomerMessage",context);
                return RedirectToPage("/CustomerPages/CarInformation");
            }
            RentingTransaction rentingTransaction = new RentingTransaction();
            rentingTransaction.RentingDate = DateTime.Now;
            rentingTransaction.TotalPrice = Total;
            rentingTransaction.CustomerId = customerId.Value;
            rentingTransaction.RentingStatus = 1;
            foreach(var item in cart)
            {
                //check if any car do not have day for rent
                if(item.TotalDays > 0)
                rentingTransaction.RentingDetails.Add(
                    new RentingDetail
                    {
                        CarId = item.CarInformation.CarId,
                        StartDate = item.StartDate,
                        EndDate = item.EndDate,
                        Price = item.CarInformation.CarRentingPricePerDay * item.TotalDays, 
                    }
                );  
            }
            string token = HttpContext.Session.GetString("token");
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            client.BaseAddress = new Uri("http://localhost:5071/api/");
            var carInfoJson = JsonConvert.SerializeObject(rentingTransaction);
            var content = new StringContent(carInfoJson, Encoding.UTF8, "application/json");
            var response = await client.PostAsync("RentingTransaction", content);
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
            }
            else
            {
                // Handle the error accordingly.
                ModelState.AddModelError(string.Empty, "Failed to retrieve suppliers.");
            }
            HttpContext.Session.Remove("cart");
            HttpContext.Session.SetString("CustomerMessage", "Renting Success!");
            return RedirectToPage("/CustomerPages/CarInformation");
        }

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].CarInformation.CarId == id)
                {
                    return i;
                }
            }
            return -1;
        }

        private async Task<CarInformation> GetCarInformationAsync(int id)
        {
            CarInformation carInformation = new CarInformation();
            string token = HttpContext.Session.GetString("token");
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var response = await client.GetAsync("CarInformation/" + id.ToString());

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    carInformation = JsonConvert.DeserializeObject<CarInformation>(responseContent);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            return carInformation;
        }
        private async Task<List<bool>> CheckCarExist(List<RentingDetail> rentingDetails)
        {
            string token = HttpContext.Session.GetString("token");
            List<bool> carExist = new List<bool>();
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            client.BaseAddress = new Uri("http://localhost:5071/api/");
            var carInfoJson = JsonConvert.SerializeObject(rentingDetails);
            var content = new StringContent(carInfoJson, Encoding.UTF8, "application/json");
            var response = await client.PostAsync("RentingDetail/check", content);

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/CustomerPages/CarInformation.cshtml
@page
@model FUCarRentingSystemFE.Pages.CustomerPages.CarInformationModel

@{
    ViewData["Title"] = "CarInformation";
}
<h1>CarInformation</h1>
<style>
    /* Style for the notification container */
    .notification {
        position: fixed;
        top: 20px;
        right: 20px;
        background-color: #333;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
        z-index: 9999; /* Ensure it appears on top of other elements */
    }

    /* Style for the notification text */
    .notification-text {
        font-size: 16px;
    }
</style>
<form method="post">
    <div class="form-group">
        <label asp-for="Keyword" class="control-label">Search:</label>
        <input asp-for="Keyword" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>
@if (Model.CustomerMessage != null)
{
    <div class="notification">
        <span class="notification-text">@Model.CustomerMessage</span>
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].CarName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].CarDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].NumberOfDoors)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].SeatingCapacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].FuelType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].CarRentingPricePerDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].Manufacturer.ManufacturerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarInformation[0].Supplier.SupplierName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.CarInformation) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CarName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfDoors)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeatingCapacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuelType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarRentingPricePerDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer.ManufacturerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.SupplierName)
            </td>
            <td>
                 <a asp-page="/CustomerPages/Cart" asp-page-handler="buynow" asp-route-id="@item.CarId">Rent</a>
            </td>
        </tr>
}
    </tbody>
</table>

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/CustomerPages/Cart.cshtml
@page
@model FUCarRentingSystemFE.Pages.CustomerPages.CartModel
@{
    ViewData["Title"] = "Cart";
}
<style>
    /* Style for the alert message */
    .alert {
        background-color: #f44336;
        color: white;
        padding: 10px;
        margin-bottom: 20px;
        text-align: center;
    }

    /* Style for the table */
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Style for table headers */
    th {
        background-color: #f2f2f2;
        text-align: left;
        padding: 8px;
    }

    /* Style for table cells */
    td {
        padding: 8px;
    }

    /* Style for the "Update" and "Buy now" buttons */
    input[type="submit"] {
        background-color: #008CBA;
        color: white;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
    }

    /* Style for the "Continue Shopping" link */
    a {
        display: inline-block;
        margin-top: 10px;
        padding: 5px 10px;
        text-decoration: none;
        border-radius: 3px;
    }
</style>

@if (TempData["Message"] != null)
{
    <div class="alert">@TempData["Message"]</div>
}
<h3>Cart</h3>
    <form method="post" asp-page="cart">
        <table border="1">
            <tr>
                <th>Action</th>
                <th>Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Total Days</th></>
                <th>Price</th>
                <th>Sub Total</th>
            </tr>
            @foreach (var item in Model.cart)
            {
                <tr align="center">
                    <td align="center">
                    <a asp-page="cart" asp-page-handler="delete" asp-route-id="@item.CarInformation.CarId">X</a>
                    </td>
                <td>@item.CarInformation.CarName</td>
                <td class="form-group">
                    <label asp-for="@item.StartDate"></label>
                    <input name="startDate" asp-for="@item.StartDate" class="form-control" min="@DateTime.Now.ToString("yyyy-MM-dd")" value="@item.StartDate.ToString("yyyy-MM-dd")" type="date" oninput="calculateDays(this)" />
                </td>
                <td class="form-group">
                    <label asp-for="@item.EndDate"></label>
                    <input name="endDate" asp-for="@item.EndDate" class="form-control" min="@DateTime.Now.ToString("yyyy-MM-dd")" value="@item.EndDate.ToString("yyyy-MM-dd")"  type="date" oninput="calculateDays(this)" />
                </td>
                <td id="daysCount">@item.TotalDays</td>
                <input type="hidden" name="daysCount" value="@item.TotalDays" />
                <td id="price" value=@item.CarInformation.CarRentingPricePerDay>@item.CarInformation.CarRentingPricePerDay</td>
                <td>@(item.CarInformation.CarRentingPricePerDay * item.TotalDays)</td>
                <input type="hidden" name="total" value="@(item.CarInformation.CarRentingPricePerDay * item.TotalDays)" />
                </tr>
            }
            <tr>
                <td colspan="6" align="right">Total</td>
                <td align="center">@Model.Total</td>
            </tr>
       
        </table>
    <input type="submit" value="Update" asp-page-handler="update" />
    <input type="submit" value="Rent now" asp-page-handler="buynow" asp-route-total="@Model.Total"/>
    </form>

    <a asp-page="/CustomerPages/CarInformation">Continue Renting</a>

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/CustomerPages/ChangeInformation.cshtml
@page
@model FUCarRentingSystemFE.Pages.CustomerPages.ChangeInformationModel

@{
    ViewData["Title"] = "ChangeInformation";
}

<h1>ChangeInformation</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Customer.CustomerId" />
            <input type="hidden" asp-for="Customer.CustomerStatus" />
            <div class="form-group">
                <label asp-for="Customer.CustomerName" class="control-label"></label>
                <input asp-for="Customer.CustomerName" class="form-control" />
                <span asp-validation-for="Customer.CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Telephone" class="control-label"></label>
                <input asp-for="Customer.Telephone" class="form-control" />
                <span asp-validation-for="Customer.Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Email" class="control-label"></label>
                <input asp-for="Customer.Email" class="form-control" />
                <span asp-validation-for="Customer.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.CustomerBirthday" class="control-label"></label>
                <input asp-for="Customer.CustomerBirthday" class="form-control" type="date"/>
                <span asp-validation-for="Customer.CustomerBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Password" class="control-label"></label>
                <input asp-for="Customer.Password" class="form-control" type="password" required/>
                <span asp-validation-for="Customer.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}