FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/AdminPages/CarInformationManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusinessObjects.Models;
using Newtonsoft.Json;
using System.Dynamic;
using System.Text;
using System.Net.Http.Headers;
using System.Net.Http;

namespace FUCarRentingSystemFE.Pages.AdminPages.CarInformationManagement
{
    public class CreateModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public CreateModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        [BindProperty]
        public byte CarStatus { get; set; } = 1;
        public async Task<IActionResult> OnGetAsync()
        {
            string adminId = HttpContext.Session.GetString("Admin") ?? null;
            if (adminId != "Admin")
                return RedirectToPage("/NotAuthorized");
            string token = HttpContext.Session.GetString("token") ?? null;
            List<Manufacturer> manufacturers = new List<Manufacturer>();        
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var response = await client.GetAsync("Manufacturer");
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    manufacturers = JsonConvert.DeserializeObject<List<Manufacturer>>(responseContent);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve manufacturers.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }


            List<Supplier> suppliers = new List<Supplier>();
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var response = await client.GetAsync("Supplier");
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    suppliers = JsonConvert.DeserializeObject<List<Supplier>>(responseContent);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve suppliers.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            ViewData["ManufacturerId"] = new SelectList(manufacturers, "ManufacturerId", "ManufacturerName");
            ViewData["SupplierId"] = new SelectList(suppliers, "SupplierId", "SupplierName");
            return Page();
        }

        [BindProperty]
        public CarInformation CarInformation { get; set; } = default!;
       
        public async Task<IActionResult> OnPostAsync()
        {
            string token = HttpContext.Session.GetString("token") ?? null;
            CarInformation.CarStatus = CarStatus;
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var carInfoJson = JsonConvert.SerializeObject(CarInformation);
                var content = new StringContent(carInfoJson, Encoding.UTF8, "application/json");
                var response = await client.PostAsync("CarInformation", content);
                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve suppliers.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            TempData["SuccessMessage"] = "Car "+ CarInformation.CarName +" created successfully.";
            return RedirectToPage("./Index");
        }
    }
}

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/AdminPages/CarInformationManagement/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Models;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace FUCarRentingSystemFE.Pages.AdminPages.CarInformationManagement
{
    public class DeleteModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public DeleteModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [BindProperty]
      public CarInformation CarInformation { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            string adminId = HttpContext.Session.GetString("Admin") ?? null;
            if (adminId != "Admin")
                return RedirectToPage("/NotAuthorized");
            string token = HttpContext.Session.GetString("token") ?? null;
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var response = await client.GetAsync("CarInformation/" + id.ToString());

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    CarInformation = JsonConvert.DeserializeObject<CarInformation>(responseContent);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            string token = HttpContext.Session.GetString("token") ?? null;
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            client.BaseAddress = new Uri("http://localhost:5071/api/");
            var response = await client.DeleteAsync("CarInformation/" + CarInformation.CarId.ToString());

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Car information deleted successfully.";
            }
            return RedirectToPage("/AdminPages/CarInformationManagement/Index");
        }
    }
}

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/AdminPages/CarInformationManagement/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Models;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace FUCarRentingSystemFE.Pages.AdminPages.CarInformationManagement
{
    public class DetailsModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public DetailsModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public CarInformation CarInformation { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            string adminId = HttpContext.Session.GetString("Admin") ?? null;
            if (adminId != "Admin")
                return RedirectToPage("/NotAuthorized");
            string token = HttpContext.Session.GetString("token") ?? null;
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/");
                var response = await client.GetAsync("CarInformation/" + id.ToString());

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    CarInformation = JsonConvert.DeserializeObject<CarInformation>(responseContent);
                }
                else
                {
                    // Handle the error accordingly.
                    ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                }
            }
            catch (Exception ex)
            {
                // Handle any exceptions that may occur during the API call.
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            return Page();
        }
    }
}

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/AdminPages/RentingTransactionManagement/RentingTransactionList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Models;
using Newtonsoft.Json;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using System.Drawing;
using ClosedXML.Excel;
using System.Net.Http.Headers;

namespace FUCarRentingSystemFE.Pages.AdminPages.RentingTransactionManagement
{
    public class RentingTransactionListModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public RentingTransactionListModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        [BindProperty(SupportsGet = true)]
        public DateTime? startDate { get; set; }
        [BindProperty(SupportsGet = true)]
        public DateTime? endDate { get; set; }
        public IList<RentingTransaction> RentingTransaction { get;set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            string adminId = HttpContext.Session.GetString("Admin") ?? null;
            if (adminId != "Admin")
                return RedirectToPage("/NotAuthorized");
            string token = HttpContext.Session.GetString("token") ?? null;
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                client.BaseAddress = new Uri("http://localhost:5071/api/"); 
                var response = await client.GetAsync("RentingTransaction"); 

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync();
                    RentingTransaction = JsonConvert.DeserializeObject<List<RentingTransaction>>(responseContent);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (startDate == null || endDate == null)
                return RedirectToPage("./RentingTransactionList");
            else
                try
                {
                    string token = HttpContext.Session.GetString("token") ?? null;
                    var client = _httpClientFactory.CreateClient();
                    client.BaseAddress = new Uri("http://localhost:5071/api/");
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    var response = await client.GetAsync("RentingTransaction/search?startDate=" + startDate.Value.ToString("MM-dd-yyyy") + "&endDate=" + endDate.Value.ToString("MM-dd-yyyy"));

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();
                        RentingTransaction = JsonConvert.DeserializeObject<List<RentingTransaction>>(responseContent);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Failed to retrieve car information.");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                }
            return Page();
        }

        public IActionResult OnPostCreateReport()
        {
            var RentingDate = Request.Form["RentingDate"];
            var Price = Request.Form["Price"];
            var RentingStatus = Request.Form["RentingStatus"];
            var Customer = Request.Form["Customer"];
            using (var workbook = new XLWorkbook())
            {
                IXLWorksheet worksheet =
                workbook.Worksheets.Add("RentingTransactions");
                worksheet.Cell(1, 1).Value = "Num";
                worksheet.Cell(1, 2).Value = "Renting Date";
                worksheet.Cell(1, 3).Value = "Price";
                worksheet.Cell(1, 4).Value = "Renting Status";
                worksheet.Cell(1, 5).Value = "Customer Name";

                IXLRange range = worksheet.Range(worksheet.Cell(1, 1).Address, worksheet.Cell(1, 5).Address);
                range.Style.Fill.SetBackgroundColor(XLColor.Almond);
                int cellId = 1;
                for (int i = 0; i < RentingDate.Count; i++)
                {
                    cellId++;
                    worksheet.Cell(cellId, 1).Value = (cellId - 1);
                    worksheet.Cell(cellId, 2).Value = RentingDate[i];
                    worksheet.Cell(cellId, 3).Value = Double.Parse(Price[i]);
                    worksheet.Cell(cellId, 4).Value = int.Parse(RentingStatus[i]);
                    worksheet.Cell(cellId, 5).Value = Customer[i];
                }
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

                    var strDate = DateTime.Now.ToString("ddMMyyyy");
                    string filename = string.Format($"RentingTransactions_{strDate}.xlsx");

                    return File(content, contentType, filename);
                }
            }
            return Page();
        }
    }
}

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/AdminPages/RentingTransactionManagement/RentingDetailList.cshtml
@page
@model FUCarRentingSystemFE.Pages.AdminPages.RentingTransactionManagement.RentingDetailListModel

@{
    ViewData["Title"] = "RentingDetailList";
    Layout = "_AdminLayout";
}

<h1>Renting Detail</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RentingDetail[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentingDetail[0].EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentingDetail[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentingDetail[0].Car)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.RentingDetail) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FormattedStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FormattedEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Car.CarName)
            </td>
        </tr>
}
    </tbody>
</table>

FUCarRentingSystemFE/FUCarRentingSystemFE/Pages/AdminPages/RentingTransactionManagement/RentingTransactionList.cshtml
@page
@model FUCarRentingSystemFE.Pages.AdminPages.RentingTransactionManagement.RentingTransactionListModel

@{
    ViewData["Title"] = "RentingTransactionList";
    Layout = "_AdminLayout";
}

<h1>RentingTransactionList</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="startDate" class="control-label">Search:</label>
        <input asp-for="startDate" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" type="date" />
    </div>
    <div class="form-group">
        <label asp-for="endDate" class="control-label">Search:</label>
        <input asp-for="endDate" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" type="date" />
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RentingTransaction[0].RentingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentingTransaction[0].TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentingTransaction[0].RentingStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentingTransaction[0].Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.RentingTransaction != null)
        {
            @foreach (var item in Model.RentingTransaction)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FormattedRentingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RentingStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.CustomerName)
                    </td>
                    <td>
                        <a asp-page="./RentingDetailList" asp-route-id="@item.RentingTransationId">Details</a>
                    </td>
                </tr>
            }

        }
        else
        {
            <p>No data available</p>
        }      
    </tbody>
</table>
<form method="post" asp-page-handler="createreport">
    @foreach (var transaction in Model.RentingTransaction)
    {
        <input type="hidden" name="RentingDate" value="@transaction.RentingDate" />
        <input type="hidden" name="Price" value="@transaction.TotalPrice" />
        <input type="hidden" name="RentingStatus" value="@transaction.RentingStatus" />
        <input type="hidden" name="Customer" value="@transaction.Customer.CustomerName" />
        <!-- Repeat this line for each property you want to include -->
    }
    <button type="submit" class="btn btn-primary">Create Report</button>
</form>